# Generated by Django 2.2.2 on 2020-04-13 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '课程种类表', 'verbose_name_plural': '课程种类表'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程表', 'verbose_name_plural': '课程表'},
        ),
        migrations.AlterField(
            model_name='course',
            name='creatDatetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 13, 14, 39, 2, 982851), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '免费'), (1, '收费')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='course',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='课程介绍'),
        ),
        migrations.AlterField(
            model_name='course',
            name='userBuyer',
            field=models.ManyToManyField(blank=True, related_name='userBuyer_set', to='user.User', verbose_name='购买用户'),
        ),
        migrations.AlterField(
            model_name='course',
            name='userShoppingcart',
            field=models.ManyToManyField(blank=True, related_name='userShoppingcart_set', to='user.User', verbose_name='加入购物车的用户'),
        ),
    ]
