# Generated by Django 2.2.2 on 2020-04-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100)),
                ('session_value', models.CharField(max_length=100)),
                ('expire_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
